"""Typed runtime context ports for LiveRuntime delegates."""

from __future__ import annotations

from typing import Any, Protocol

from lightfee.config.schema import AppConfig
from lightfee.core.contracts import VenueAdapter
from lightfee.core.domain import Venue
from lightfee.engine.state import EngineState
from lightfee.persistence.journal import Journal
from lightfee.persistence.snapshot_store import SnapshotStore


class RuntimeCommonContext(Protocol):
    @property
    def state(self) -> EngineState: ...

    @property
    def config(self) -> AppConfig: ...

    @property
    def journal(self) -> Journal: ...

    @property
    def venue_contracts(self) -> Any: ...

    @property
    def order_truth(self) -> Any: ...

    @property
    def lifecycle_closure(self) -> Any: ...

    @property
    def quote_truth(self) -> Any: ...

    @property
    def catalog_support(self) -> Any: ...

    @property
    def exchange_truth(self) -> Any: ...


class MarketDataRuntimeContext(RuntimeCommonContext, Protocol):
    @property
    def snapshot_store(self) -> SnapshotStore: ...

    @property
    def venue_adapters(self) -> dict[Venue, VenueAdapter]: ...

    @property
    def local_l2_runtime(self) -> Any: ...

    @property
    def funding_risk_runtime(self) -> Any: ...

    @property
    def ws_bbo_cache(self) -> Any: ...

    @property
    def l2_data_plane(self) -> Any: ...

    @property
    def ws_bbo_data_plane(self) -> Any: ...

    @property
    def entry_l2_sessions(self) -> Any: ...

    @property
    def entry_readiness_provider(self) -> Any: ...

    @property
    def ws_bbo_rest_refresher(self) -> Any: ...

    @ws_bbo_rest_refresher.setter
    def ws_bbo_rest_refresher(self, value: Any) -> None: ...

    @property
    def entry_open_interest_refresher(self) -> Any: ...

    @entry_open_interest_refresher.setter
    def entry_open_interest_refresher(self, value: Any) -> None: ...

    @property
    def _entry_bbo_subscription_budgeted_keys(self) -> set[tuple[str, str]]: ...

    @_entry_bbo_subscription_budgeted_keys.setter
    def _entry_bbo_subscription_budgeted_keys(
        self,
        value: set[tuple[str, str]],
    ) -> None: ...

    @property
    def _entry_bbo_subscription_budget_excluded_keys(self) -> set[tuple[str, str]]: ...

    @_entry_bbo_subscription_budget_excluded_keys.setter
    def _entry_bbo_subscription_budget_excluded_keys(
        self,
        value: set[tuple[str, str]],
    ) -> None: ...

    @property
    def _entry_bbo_subscription_per_venue_budget(self) -> int: ...

    @_entry_bbo_subscription_per_venue_budget.setter
    def _entry_bbo_subscription_per_venue_budget(self, value: int) -> None: ...

    @property
    def _last_snapshot_freshness_filter_blockers(self) -> Any: ...

    @_last_snapshot_freshness_filter_blockers.setter
    def _last_snapshot_freshness_filter_blockers(self, value: Any) -> None: ...

    @property
    def _last_snapshot_freshness_filter_samples(self) -> Any: ...

    @_last_snapshot_freshness_filter_samples.setter
    def _last_snapshot_freshness_filter_samples(self, value: Any) -> None: ...

    @property
    def _snapshot_freshness_decision_last_emit_ms(self) -> dict[Any, int]: ...

    @property
    def _snapshot_freshness_decision_suppressed(self) -> Any: ...

    @property
    def _SNAPSHOT_FRESHNESS_DECISION_LOG_INTERVAL_MS(self) -> int: ...

    def get_venue_adapter(self, venue: Venue) -> VenueAdapter | None: ...

    def _refresh_runtime_market_data_config_state(self) -> None: ...

    def _entry_readiness_provider_name(self) -> str: ...

    def _local_l2_effective_enabled(self) -> bool: ...

    def _entry_readiness_provider_uses_local_l2(self) -> bool: ...

    def _entry_readiness_provider_uses_ws_bbo(self) -> bool: ...

    def _entry_quote_lease_max_age_ms(self) -> int: ...

    def _entry_local_l2_stale_after_ms(self) -> int: ...

    async def _filter_symbols_supported_by_venue(
        self,
        venue: Venue,
        adapter: VenueAdapter,
        symbols: list[str],
        *,
        skip_event_kind: str,
        fail_closed_on_catalog_unavailable: bool = False,
    ) -> list[str]: ...

    def _append_runtime_diagnostic_event(self, *args: Any, **kwargs: Any) -> None: ...

    def _candidate_pair_id(self, candidate: Any) -> str: ...

    def _clear_local_l2_runtime_state(self) -> None: ...

    def _record_snapshot_scoped_status(self, *args: Any, **kwargs: Any) -> None: ...

    def _candidate_requires_sidecar_perp_liquidity(self, candidate: Any) -> bool: ...

    def _entry_liquidity_qualification_decisions(self, *args: Any, **kwargs: Any) -> Any: ...

    def _liquidity_degraded_reason_blocks_symbol(self, reason: str, symbol: str) -> bool: ...

    def _liquidity_lifecycle_payload(self, *args: Any, **kwargs: Any) -> dict: ...

    def _select_v1_entry_tracked_scope(self, candidates: Any) -> tuple[list, list]: ...


class EntryGateRuntimeContext(RuntimeCommonContext, Protocol):
    @property
    def snapshot_store(self) -> SnapshotStore: ...

    @property
    def venue_adapters(self) -> dict[Venue, VenueAdapter]: ...

    @property
    def entry_readiness_provider(self) -> Any: ...

    @property
    def entry_l2_sessions(self) -> Any: ...

    @property
    def local_l2_runtime(self) -> Any: ...

    @property
    def ws_bbo_cache(self) -> Any: ...

    @property
    def recovery_ledger(self) -> Any: ...

    @property
    def _tracked_primary_pair_ids(self) -> set[str]: ...

    @_tracked_primary_pair_ids.setter
    def _tracked_primary_pair_ids(self, value: set[str]) -> None: ...

    @property
    def _symbol_admission_blocked_until_ms(self) -> dict[tuple[str, str], int]: ...

    @property
    def _venue_cooldown_until_ms(self) -> Any: ...

    @property
    def _zero_fill_cooldown_until_ms(self) -> Any: ...

    @property
    def _post_only_reject_cooldown_until_ms(self) -> Any: ...

    @property
    def _last_candidate_catalog_filter_blockers(self) -> Any: ...

    @_last_candidate_catalog_filter_blockers.setter
    def _last_candidate_catalog_filter_blockers(self, value: Any) -> None: ...

    @property
    def _last_candidate_catalog_filter_samples(self) -> Any: ...

    @_last_candidate_catalog_filter_samples.setter
    def _last_candidate_catalog_filter_samples(self, value: Any) -> None: ...

    @property
    def _last_entry_admission_filter_blockers(self) -> Any: ...

    @_last_entry_admission_filter_blockers.setter
    def _last_entry_admission_filter_blockers(self, value: Any) -> None: ...

    @property
    def _last_entry_admission_filter_samples(self) -> Any: ...

    @_last_entry_admission_filter_samples.setter
    def _last_entry_admission_filter_samples(self, value: Any) -> None: ...

    @property
    def _last_snapshot_freshness_filter_blockers(self) -> Any: ...

    @_last_snapshot_freshness_filter_blockers.setter
    def _last_snapshot_freshness_filter_blockers(self, value: Any) -> None: ...

    @property
    def _last_snapshot_freshness_filter_samples(self) -> Any: ...

    @_last_snapshot_freshness_filter_samples.setter
    def _last_snapshot_freshness_filter_samples(self, value: Any) -> None: ...

    @property
    def _last_no_entry_diag_fingerprint(self) -> str: ...

    @_last_no_entry_diag_fingerprint.setter
    def _last_no_entry_diag_fingerprint(self, value: str) -> None: ...

    @property
    def _last_no_entry_diag_ts_ms(self) -> int: ...

    @_last_no_entry_diag_ts_ms.setter
    def _last_no_entry_diag_ts_ms(self, value: int) -> None: ...

    @property
    def _last_no_entry_full_diag_ts_ms(self) -> int: ...

    @_last_no_entry_full_diag_ts_ms.setter
    def _last_no_entry_full_diag_ts_ms(self, value: int) -> None: ...

    @property
    def _last_no_entry_full_diag_reason(self) -> str: ...

    @_last_no_entry_full_diag_reason.setter
    def _last_no_entry_full_diag_reason(self, value: str) -> None: ...

    @property
    def _last_no_entry_summary_fingerprint(self) -> str: ...

    @_last_no_entry_summary_fingerprint.setter
    def _last_no_entry_summary_fingerprint(self, value: str) -> None: ...

    @property
    def _no_entry_suppressed_full_payload_count(self) -> int: ...

    @_no_entry_suppressed_full_payload_count.setter
    def _no_entry_suppressed_full_payload_count(self, value: int) -> None: ...

    @property
    def _last_no_entry_diagnostics(self) -> Any: ...

    @_last_no_entry_diagnostics.setter
    def _last_no_entry_diagnostics(self, value: Any) -> None: ...

    @property
    def _SYMBOL_ADMISSION_BLOCK_TTL_MS(self) -> int: ...

    @property
    def _ENTRY_ADMISSION_VENUE_DEGRADED_LOG_INTERVAL_MS(self) -> int: ...

    @property
    def _NO_ENTRY_DIAGNOSTICS_COMPACT_INTERVAL_MS(self) -> int: ...

    @property
    def _NO_ENTRY_DIAGNOSTICS_FULL_INTERVAL_MS(self) -> int: ...

    @property
    def _ENTRY_BLOCKED_LOCAL_L2_SELECTION_LOG_INTERVAL_MS(self) -> int: ...

    @property
    def _CANDIDATE_SYMBOL_SKIPPED_LOG_INTERVAL_MS(self) -> int: ...

    @property
    def _V1_ENTRY_LIFECYCLE_SELECTION_BLOCKERS(self) -> Any: ...

    def get_venue_adapter(self, venue: Venue) -> VenueAdapter | None: ...

    def _append_runtime_diagnostic_event(self, *args: Any, **kwargs: Any) -> None: ...

    async def _filter_symbols_supported_by_venue(self, *args: Any, **kwargs: Any) -> Any: ...

    def _candidate_pair_id(self, *args: Any, **kwargs: Any) -> Any: ...

    def _candidate_uses_venue(self, *args: Any, **kwargs: Any) -> Any: ...

    def _cached_entry_balance_snapshot(self, *args: Any, **kwargs: Any) -> Any: ...

    def _store_entry_balance_snapshot(self, *args: Any, **kwargs: Any) -> None: ...

    def _entry_admission_evidence(self, *args: Any, **kwargs: Any) -> Any: ...

    def _entry_admission_margin_buffer_bps(self) -> float: ...

    def _hyperliquid_entry_required_initial_margin_quote(self, *args: Any, **kwargs: Any) -> Any: ...

    def _record_symbol_admission_block(self, *args: Any, **kwargs: Any) -> Any: ...

    def _v1_lifecycle_entry_gate_decision(self) -> Any: ...

    def _v1_lifecycle_closure_blocks_candidate(self, *args: Any, **kwargs: Any) -> Any: ...

    def _v1_lifecycle_runtime_gate_reason(self, *args: Any, **kwargs: Any) -> Any: ...

    def _v1_tradeable_no_entry_reason(self, *args: Any, **kwargs: Any) -> Any: ...

    def _entry_l2_readiness_diagnostics_payload(self) -> dict: ...

    def _entry_readiness_provider_name(self) -> str: ...

    def _entry_readiness_provider_uses_local_l2(self) -> bool: ...

    def _entry_readiness_provider_uses_ws_bbo(self) -> bool: ...

    def _entry_local_l2_stale_after_ms(self) -> int: ...

    def _entry_ws_bbo_subscription_blocker(self, *args: Any, **kwargs: Any) -> Any: ...

    def _local_l2_effective_enabled(self) -> bool: ...

    def _market_quote_lookup(self, *args: Any, **kwargs: Any) -> Any: ...

    def _no_tradeable_reason_from_candidate_blockers(self, *args: Any, **kwargs: Any) -> Any: ...

    def _payload_fingerprint(self, *args: Any, **kwargs: Any) -> Any: ...

    def _snapshot_domain_budget_ms(self, *args: Any, **kwargs: Any) -> Any: ...

    def _snapshot_quote_observed_at_ms(self, *args: Any, **kwargs: Any) -> Any: ...

    def _ws_bbo_selection_blocker_family(self, *args: Any, **kwargs: Any) -> Any: ...


class EntryDispatchRuntimeContext(RuntimeCommonContext, Protocol):
    @property
    def venue_adapters(self) -> dict[Venue, VenueAdapter]: ...

    @property
    def entry_readiness_provider(self) -> Any: ...

    @property
    def local_l2_runtime(self) -> Any: ...

    @property
    def entry_executor(self) -> Any: ...

    @property
    def _recovery_dedup_index(self) -> dict[str, str]: ...

    def get_venue_adapter(self, *args: Any, **kwargs: Any) -> Any: ...

    def _safe_positive_float(self, *args: Any, **kwargs: Any) -> Any: ...

    def _candidate_pair_id(self, *args: Any, **kwargs: Any) -> Any: ...

    def _entry_admission_reject_metadata(self, *args: Any, **kwargs: Any) -> Any: ...

    def _record_symbol_admission_block(self, *args: Any, **kwargs: Any) -> Any: ...

    def _candidate_admission_block(self, *args: Any, **kwargs: Any) -> Any: ...

    def _candidate_is_tradeable_for_selection(self, *args: Any, **kwargs: Any) -> Any: ...

    def _gate_reduce_only(self, *args: Any, **kwargs: Any) -> Any: ...

    def _gate_pending_close_reconciliation(self, *args: Any, **kwargs: Any) -> Any: ...

    def _gate_passive_close_pending(self, *args: Any, **kwargs: Any) -> Any: ...

    def _gate_recovery_ledger(self, *args: Any, **kwargs: Any) -> Any: ...

    def _gate_pending_entry_dedup(self, *args: Any, **kwargs: Any) -> Any: ...

    def _gate_entry_sizing(self, *args: Any, **kwargs: Any) -> Any: ...

    def _gate_venue_cooldown(self, *args: Any, **kwargs: Any) -> Any: ...

    def _gate_zero_fill_cooldown(self, *args: Any, **kwargs: Any) -> Any: ...

    def _entry_quote_lease_max_age_ms(self, *args: Any, **kwargs: Any) -> Any: ...

    def _quote_lease_blocker_family(self, *args: Any, **kwargs: Any) -> Any: ...

    def _entry_readiness_provider_name(self, *args: Any, **kwargs: Any) -> Any: ...

    def _entry_readiness_provider_uses_quote_lease(self, *args: Any, **kwargs: Any) -> Any: ...

    def _local_l2_effective_enabled(self, *args: Any, **kwargs: Any) -> Any: ...

    def _post_only_maker_bbo_guard(self, *args: Any, **kwargs: Any) -> Any: ...

    def _entry_reject_is_post_only_would_take(self, *args: Any, **kwargs: Any) -> Any: ...

    def _record_post_only_reject_cooldown(self, *args: Any, **kwargs: Any) -> Any: ...

    def _queue_pending_residual_repair(self, *args: Any, **kwargs: Any) -> Any: ...

    async def _funding_entry_margin_evidence(
        self,
        venue: Venue,
        now_ms: int,
    ) -> dict[str, Any]: ...


class CloseRuntimeContext(RuntimeCommonContext, Protocol):
    @property
    def venue_adapters(self) -> dict[Venue, VenueAdapter]: ...

    @property
    def local_l2_runtime(self) -> Any: ...

    @property
    def ws_bbo_cache(self) -> Any: ...

    @property
    def close_executor(self) -> Any: ...

    @property
    def passive_close_executor(self) -> Any: ...

    def _flush_adapter_order_diagnostics(self, adapter: Any) -> None: ...

    def _entry_readiness_provider_uses_local_l2(self) -> bool: ...

    def _entry_readiness_provider_uses_ws_bbo(self) -> bool: ...

    def _entry_quote_lease_max_age_ms(self) -> int: ...


class PassiveMakerRuntimeContext(RuntimeCommonContext, Protocol):
    @property
    def snapshot_store(self) -> SnapshotStore: ...

    @property
    def venue_adapters(self) -> dict[Venue, VenueAdapter]: ...

    @property
    def local_l2_runtime(self) -> Any: ...

    @property
    def ws_bbo_cache(self) -> Any: ...

    @property
    def entry_executor(self) -> Any: ...

    @property
    def _maker_event_state(self) -> dict[str, object]: ...

    @property
    def _last_maker_event_ms(self) -> int: ...

    @_last_maker_event_ms.setter
    def _last_maker_event_ms(self, value: int) -> None: ...

    def _refresh_runtime_market_data_config_state(self) -> None: ...

    def _local_l2_effective_enabled(self) -> bool: ...

    def _entry_readiness_provider_uses_ws_bbo(self) -> bool: ...

    def _entry_quote_lease_max_age_ms(self) -> int: ...

    def _refresh_entry_l2_session_readiness(self, now_ms: int) -> None: ...


class ResidualRepairRuntimeContext(RuntimeCommonContext, Protocol):
    @property
    def snapshot_store(self) -> SnapshotStore: ...

    @property
    def recovery_decision(self) -> Any: ...

    def get_venue_adapter(self, venue: Venue) -> VenueAdapter | None: ...

    def _flush_adapter_order_diagnostics(self, adapter: Any) -> None: ...

    def _recovery_state_collection(self, name: str) -> list[Any]: ...

    def _venue_min_notional(self, venue: Venue, symbol: str) -> float: ...

    def _safe_positive_float(self, value: Any) -> float: ...

    def _close_reconciliation_fill_qty(self, fill: Any) -> float: ...

    def _v1_lifecycle_event_fields(
        self,
        *,
        phase: str,
        owner_id: str = "",
        row_key: str = "",
        now_ms: int | None = None,
    ) -> dict[str, str]: ...


class RuntimeContext(
    MarketDataRuntimeContext,
    EntryGateRuntimeContext,
    EntryDispatchRuntimeContext,
    CloseRuntimeContext,
    PassiveMakerRuntimeContext,
    ResidualRepairRuntimeContext,
    Protocol,
):
    """Compatibility aggregate for delegates not yet narrowed to a domain port."""
